export const statistics = {
  totalPromises: 524,
  fulfilledPromises: 142,
  inProcessPromises: 230,
  brokenPromises: 152,
  totalPoliticians: 105,
  activeUsers: 1420,
};

export const politicians = [
  {
    id: "1",
    name: "Ahmad Subarjo",
    party: "Partai Harapan Rakyat",
    position: "Bupati Kabupaten X",
    imageUrl: "https://i.pravatar.cc/150?u=1",
    fulfillmentRate: 85,
    promisesCount: 15,
  },
  {
    id: "2",
    name: "Siti Rahmawati",
    party: "Partai Demokrasi Sejahtera",
    position: "Anggota DPR RI",
    imageUrl: "https://i.pravatar.cc/150?u=2",
    fulfillmentRate: 78,
    promisesCount: 22,
  },
  {
    id: "3",
    name: "Budi Santoso",
    party: "Partai Karya Bangsa",
    position: "Walikota Y",
    imageUrl: "https://i.pravatar.cc/150?u=3",
    fulfillmentRate: 65,
    promisesCount: 10,
  },
  {
    id: "4",
    name: "Agus Yudhoyono",
    party: "Partai Adil Makmur",
    position: "Gubernur Z",
    imageUrl: "https://i.pravatar.cc/150?u=4",
    fulfillmentRate: 32,
    promisesCount: 45,
  },
  {
    id: "5",
    name: "Dewi Lestari",
    party: "Partai Indonesia Maju",
    position: "Anggota DPRD",
    imageUrl: "https://i.pravatar.cc/150?u=5",
    fulfillmentRate: 21,
    promisesCount: 12,
  },
];

export const trendingPromises = [
  {
    id: "p1",
    politicianId: "1",
    politicianName: "Ahmad Subarjo",
    politicianImageUrl: "https://i.pravatar.cc/150?u=1",
    title: "Membangun 5 RSUD Baru dalam 3 Tahun",
    status: "Dalam Proses", // Belum Dimulai, Dalam Proses, Selesai, Ingkar
    deadline: "2025-12-31",
    reportsCount: 124,
  },
  {
    id: "p2",
    politicianId: "4",
    politicianName: "Agus Yudhoyono",
    politicianImageUrl: "https://i.pravatar.cc/150?u=4",
    title: "Membuka 100,000 Lapangan Kerja Baru",
    status: "Belum Dimulai",
    deadline: "2026-06-30",
    reportsCount: 89,
  },
  {
    id: "p3",
    politicianId: "2",
    politicianName: "Siti Rahmawati",
    politicianImageUrl: "https://i.pravatar.cc/150?u=2",
    title: "Subsidi Pendidikan hingga Perguruan Tinggi",
    status: "Selesai",
    deadline: "2024-12-31",
    reportsCount: 305,
  },
  {
    id: "p4",
    politicianId: "5",
    politicianName: "Dewi Lestari",
    politicianImageUrl: "https://i.pravatar.cc/150?u=5",
    title: "Normalisasi Sungai Anti Banjir",
    status: "Ingkar",
    deadline: "2023-12-31",
    reportsCount: 412,
  },
];
